export const CREATE_ESTABLISHMENT = 'CREATE_ESTABLISHMENT';
export const CREATE_ESTABLISHMENT_SUCCESS = 'CREATE_ESTABLISHMENT_SUCCESS';
export const CREATE_ESTABLISHMENT_FAILURE = 'CREATE_ESTABLISHMENT_FAILURE';
export const CLEAR_ESTABLISHMENT = 'CLEAR_ESTABLISHMENT';